### ISSUE TITLE
Possibilities with Python 3

### ISSUE THREAD

**Issue by rosiecakes** [makaimc/underwear#9]
Hi Matt! Decided to give this a run after hearing your plug for it on the TPTM podcast. But it looks like it depends on Fabric which is apparently Python 2 only. Wondering if there were any plans to move this to invoke or create Py3 compatibility otherwise?

**Comment by mattmakai** [comment]
yea actually I'm working with Ansible 2.3 for an update to my book. that'll make it possible to update to Python 3. I'll remove Fabric and just use Ansible going forward. if I get some time to work on it... :)

**Comment by rosiecakes** [comment]
oh sweet that's even better! will look forward to the update, I got your book too ❤️ thanks!
